In [8]:
import cv2
import numpy as np

In [7]:
image = cv2.imread('./images/templateshape.PNG')
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow('Original', image)
cv2.waitKey(0)

template = cv2.imread('./images/3Shapes.PNG')
gray = cv2.cvtColor(template, cv2.COLOR_BGR2GRAY)

ret, thres1 = cv2.threshold(image_gray, 127, 255, 0)
ret, thres2 = cv2.threshold(gray, 127, 255, 0)

contours, hierarchy = cv2.findContours(thres1, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

contours = sorted(contours, key = cv2.contourArea, reverse=True)

template_contours = contours[1]

contours, hierarchy = cv2.findContours(thres2, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

for c in contours:
    match = cv2.matchShapes(template_contours, c, 1, 0.0)
    print(match)
    #print(c)
    if match < 0.75:
        closest_contour = c
    else:
        closest_contour = []

#print(closest_contour)
cv2.drawContours(template, closest_contour, -1, (0,255,0), 3)        
cv2.imshow('Result', template)
cv2.waitKey(0)
cv2.destroyAllWindows()

0.7463538386001347
0.25255930859741693
0.21683905613397747
0.6121728712263059
0.2204094292022647
[[[650  23]]

 [[651  22]]

 [[652  23]]

 [[651  24]]]
